apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blog-full-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: blog-full
    spec:
      containers:
      - name: wp
        image: wordpress:php7.0
        ports:
        - name: fullblogport
          containerPort: 80
        env:
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            value: example
          - name: WORDPRESS_DB_HOST
            value: 127.0.0.1
      - name: db
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: example
        ports:
        - name: fullblogdbport
          containerPort: 3306