apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-db-split-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-db-split
    spec:
      containers:
      - name: db
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: example
        ports:
        - name: fullblogdbport
          containerPort: 3306
          
---
apiVersion: v1
kind: Service
metadata:
  name: wp-db-split-svc
spec:
  ports:
  - port: 3306
    nodePort: 32001
    targetPort: fullblogdbport
    protocol: TCP
  selector:
    app: wp-db-split
  type: NodePort
