apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wp-split-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-split
    spec:
      containers:
      - name: wp
        image: wordpress:php7.0
        ports:
        - name: fullblogport
          containerPort: 80
        env:
          - name: WORDPRESS_DB_USER
            value: root
          - name: WORDPRESS_DB_PASSWORD
            value: example
          - name: WORDPRESS_DB_HOST
            value: wp-db-split-svc
         
---
apiVersion: v1
kind: Service
metadata:
  name: wp-split-svc
spec:
  ports:
  - port: 8000
    nodePort: 32002
    targetPort: fullblogport
    protocol: TCP
  selector:
    app: wp-split
  type: NodePort
